openapi: 3.0.0
info:
  title: "API de administracion de carros"
  description: prueba de usar OpenAPI
  version: "1.0.0"
components:
  schemas:
    Carro:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
        marca:
          type: string
          maxLength: 10
        placa:
          type: string
        esNuevo:
          type: boolean
        soat:
          type: array
          items:
            type: integer
            format: int32
      required:
        - id
        - marca

paths:
  /carro:
    get:
      description: retorna los carros
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Carro"
